spring:
  application:
    name: spring-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 2222
#打开feign-hystrix
feign:
  hystrix:
    enabled: true

#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000