eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    appname: eureka-server
#    hostname: peer1
  server:
    enable-self-preservation: false #关闭保护
spring:
  boot:
    admin:
      client:
        url: http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
