spring:
  application:
    name: admin-ui
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"